### ISSUE TITLE
Module callbacks included twice

### ISSUE THREAD

**Issue by Fustrate** [Sorcery/sorcery#172]
### Configuration

- Sorcery Version: `0.13.0`
- Ruby Version: `2.6.0`
- Framework: `Rails 5.2.2`
- Platform: `macOS 10.14.2`

### Expected Behavior

With the ActivityLogging module enabled, have callbacks fire once.

```
Sorcery::Controller::Config.before_logout.inspect
# => [:register_logout_time_to_db]
```

### Actual Behavior

```
Sorcery::Controller::Config.before_logout.inspect
# => [:register_logout_time_to_db, :register_logout_time_to_db]
```

### Steps to Reproduce

Initializer:

`Rails.application.config.sorcery.submodules = %i[activity_logging]`

This stems from `Sorcery::Controller` being included for both `ActionController::API` and `ActionController::Base` in `engine.rb`. Both calls end up including the submodules, which in turn add the callbacks to class attributes on `Config`.

The simplest solution is probably to call `.uniq` on the array of callbacks before executing them, though there's definitely a deeper solution to be found. I can submit a PR with the quick solution if that's the road to go down.

**Comment by mladenilic** [comment]
Could be related to/fixed by #163.

**Comment by Fustrate** [comment]
I must be blind. It's definitely the same issue.

**Comment by athix** [comment]
This is an active bug though, reopening until it's fixed.

**Comment by Fustrate** [comment]
Except this is just a symptom of the same bug, is it not? Essentially making this a duplicate issue?

**Comment by athix** [comment]
The other issue is a pull request, and I feel it's appropriate to have them separate but linked. On the pull request we can discuss implementation details, and use this issue to talk about anything not specific to implementation. I imagine it also helps search visibility to have this as an issue rather than a pull request. I don't have any strong preferences though, if there's any community guidelines on how to structure issues/pull requests I would be fine using that.
