### ISSUE TITLE
Is "Simple Password Authentication" wrong?

### ISSUE THREAD

**Issue by Eiostu** [Sorcery/sorcery#182]
Hi,

If do not add a 'new' action in the controller, will there be a continuous redirect when accessing '/ login'?

```
# config / routes.rb
get 'login' => 'user_sessions # new',: as =>: login
```
```
# app / controllers / user_sessions_controller.rb
skip_before_action: require_login, only: [: index,: create]
```
```
# app / controllers / application_controller.rb
private
def not_authenticated
   redirect_to login_path, alert: "Please login first"
end
```
I am sorry if I misunderstood.

**Comment by athix** [comment]
Are you asking if `skip_before_action :require_login` must include the `:new` action? If so, yes. Otherwise when you hit the login page (`user_sessions#new`) your controller will check to see if the user is logged in, see that they are not and create an infinite redirect loop to the login page.

Your user sessions controller will probably include only the two methods required for creating a session (`new` and `create`) and destroying a session (`destroy`). In this case, you would want something like `skip_before_action :require_login, except: [:destroy]` in your UserSessionsController.

Please let me know if that answers your question!

**Comment by Eiostu** [comment]
Thank you athix.

Then, [「Simple-Password-Authentication」](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication) in the wiki, does the statement at the bottom of mean it is wrong?

All the code I showed was taken from within the wiki.

I'm sorry I didn't know how to make a pull request on the wiki and I would write it here.

And because I rely on Google translation, English may be strange.

**Comment by athix** [comment]
@Eiostu thanks for pointing that out, it does look like the wiki is incorrect. If someone would like to update it, I would appreciate the help. Otherwise I'll try to update it myself when time permits.

**Comment by Eiostu** [comment]
@athix thanks you very much!

I have updated the wiki.
