### ISSUE TITLE
Suggestion: update sample code form_tag -> form_with

### ISSUE THREAD

**Issue by neko314** [Sorcery/sorcery#194]
There's no wrong behavior, but I found `form_tag`  [here](https://github.com/Sorcery/sorcery/wiki/Simple-Password-Authentication), and I think `form_with` is better than `form_tag`.

I can't make PR against Wiki, so I make this issue.

### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.6.0`
- Framework: `rails 5.2.3`
- Platform: `macOS`

### Suggestion

```diff
-<%= form_tag user_sessions_path, :method => :post do %>
+<%= form_with url: user_sessions_path, method: :post do |f| %>
  <div class="field">
-    <%= label_tag :email %><br />
+    <%= f.label :email %><br />
-    <%= text_field_tag :email %>
+    <%= f.text_field :email %>
  </div>
  <div class="field">
-    <%= label_tag :password %><br />
+    <%= f.label :password %><br /> 
-    <%= password_field_tag :password %>
+    <%= f.password_field :password %>
  </div>
  <div class="actions">
-    <%= submit_tag "Login" %>
+    <%= f.submit "Login" %>
  </div>
<% end %>

```

**Comment by athix** [comment]
Thanks @neko314!

Yeah, unfortunately a lot of the wiki hasn't been touched since Rails 4, and the syntax is heavily outdated in several places. If you see any other issues like that and want to update them, please feel free to edit the wiki directly! I would love any extra help.

I'll go ahead and update the section you mentioned above.

**Comment by athix** [comment]
Wiki updated.
