### ISSUE TITLE
Rails 6.0.1 - Unknown column 'remember_me_token._rails'

### ISSUE THREAD

**Issue by andey** [Sorcery/sorcery#210]
### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `ruby 2.6.5p114`
- Framework: `rails 6.0.1`
- Platform: `4.14.146-93.123.amzn1.x86_64`

### Expected Behavior

No Exception

### Actual Behavior

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'remember_me_token._rails' in 'where clause': SELECT `users`.* FROM `users` WHERE `remember_me_token`.`_rails` = '---\nmessage: Il91TGlDeDh2blJpczE1QWlHdjduIg==\nexp: \'2019-11-27T22:42:17.000Z\'\npur: \n' ORDER BY `users`.`id` ASC LIMIT 1
```

### Steps to Reproduce

This error is Intermittent, and I'm unable to reproduce manually.

![Screenshot of rollbar](https://i.imgur.com/avhI30g.png)

### Context

Right now I'm splitting traffic between `rails 4.2.11.1` and `rails 6.0.1`, this error just appearing when I started sending production traffic to `rails 6.0.1`. Sorcery version has not changed.

**Comment by mladenilic** [comment]
Do you maybe use multiple DBs setup? I'm trying to figure out where did the `_rails` come from.

**Comment by andey** [comment]
@mladenilic I do indeed have multiple DBs setup using the new rails 6.0 feature, nothing custom.

**Comment by logicalgroove** [comment]
it comes from rails as I can see:

https://github.com/rails/rails/blob/37e87fd324ab94790c191fb82e902ba9d3365218/activesupport/lib/active_support/messages/metadata.rb#L14

**Comment by andey** [comment]
I totally overlooked something.

The error started to happen when I started sending traffic to `rails 6.0.1`, however all the exceptions are happening on the `rails 4.2.11.1` servers. 

I'm going to take a guess that this exception is happening when users are being served `rails 6` then get switched back to `rails 4`

**Comment by mladenilic** [comment]
Ok, so we got it figured out. Rails 4 is failing to extract message from signed cookies which include meta data, which was added much later (https://github.com/rails/rails/commit/1cda4fb5df519080032c9c0a16d3c4f8cf1f3d2c#diff-69714203ccef60fcead8d4eff741a883)

@athix: Just to be on the safe side of things, should we add a check to the `find_by_remember_me_token ` to avoid malformed queries? In this case, the `login_from_cookie` passed the entire cookie hash to the `find_by_remember_me_token`?

**Comment by athix** [comment]
@mladenilic I think it would make sense to limit the function to look only at the cookie values it expects, if it doesn't already.

I'm curious what exactly is going on here, it sounds like the symptom is Sorcery on rails 4 trying to read the wrong column for remember_me. Is this happening because it can't read the cookie and it assumes the wrong default, or does rails 6 set the column to something different which rails 4 then reads and errors out on?

**Comment by andey** [comment]
Just going to throw it out there. 

I stopped sending traffic to rails 4 approximately 2 hours ago, and I haven't seen the error again.

**Comment by mladenilic** [comment]
@athix  Rails 4 fails to read the signed cookie saved by Rails 6.

So instead of:
```
cookies.signed[:remember_me]
=> "dc5e42..."
```

It results in:
```
cookies.signed[:remember_me]
=> { _rails: "...." }
```

This invalid cookie hash gets passed to `find_by_remember_me_token` which raises the error:

instead of:
```rb
User.where(rememebr_me_toke: 'dc5e42...')
```

it does:
```rb
User.where(rememebr_me_toke: { _rails: "...." })
```

Since `find_by_remember_me_token` gets token passed to it from a cookie, which we can basically consider a user input, I think we should make sure that the token value resembles something that could be an actual token.

```rb
def find_by_remember_me_token(token)
  return false unless token.is_a? String

  ...
end
```

**Comment by mladenilic** [comment]
@athix: I think we can close this one.

**Comment by athix** [comment]
@mladenilic sounds good. It seems like in the end this was just gotchas with Rails 4, which we're deprecating going forward anyway.
