### ISSUE TITLE
suggested feature: inviting other users

### ISSUE THREAD

**Issue by BKSpurgeon** [Sorcery/sorcery#222]
inviting users feature. Here is a proposed (and very general) workflow:

1. A Logged in user has a form to invite others. An email address is accepted in the form - in a field in the form.
2. An email is generated and send to the specified email address. Presumably a unique token is created.
3. When the link is clicked, in the email that was sent, the user can simply create a user account and have all the settings associated with a particular invitation, applied to that particular user.

A hello world example demonstrated the above would likely be well received.

Would like to pull through with a PR if possible, any guidance on the above would be appreciated.

chrs

Ben

**Comment by mladenilic** [comment]
I get where you're coming from, but I think this is out of Sorcery's scope. Maybe this could be a separate gem?

**Comment by BKSpurgeon** [comment]
> I get where you're coming from, but I think this is out of Sorcery's scope. Maybe this could be a separate gem?


@mladenilic what i am proposing is a set of very general helper methods to enable this type of work flow to be cobbled. The helpers required are not unlike those used in the reset my password plugins. e.g:

When the user sends an invite, it would be nice if the invitee just clicked on a link and signed up, and had everything already set up. In order to set it up and generate that link, one would need a few basic helpers:

1. helper to generate random tokens.
2. helper to identify the random tokens.

**Comment by athix** [comment]
@BKSpurgeon I think your idea is amazing, but I agree with @mladenilic that this would be outside of Sorcery's scope. Sorcery is intended to handle just the authentication aspect of the process, and it's primary benefit over something like Devise is its lightweight nature.

What I would recommend is creating a gem that integrates with Sorcery, and provides the invite functionality you're suggesting. [Rubygems - Making your own gem guide](https://guides.rubygems.org/make-your-own-gem/)

If you would like to make that Gem, we can definitely work on making it an official extension of Sorcery. The long term plan for Sorcery 1.0 is to break out the sub-module functionalities into their own gems anyway, so that we can have both a lightweight and easy-to-use core while supporting these kinds of extensions for people that need them.

**Comment by BKSpurgeon** [comment]
@athix appreciate the response.

will certainly keep that in mind: re adding a gem for those helpers - but I cannot promise anything at this stage.

regards

Ben
