### ISSUE TITLE
 undefined local variable or method `page' for #<RSpec::ExampleGroups...>

### ISSUE THREAD

**Issue by hiendinhngoc** [Sorcery/sorcery#228]
### Configuration

- Sorcery Version: `0.14.0`
- Ruby Version: `2.7.1`
- Framework: `6.0.2.2`
- Platform: `ubuntu 18.04`

hi there, getting an issue with Rspec test  when authenticating. I followed the wiki here:
https://github.com/Sorcery/sorcery/wiki/Testing-Rails

this is my /support/authentication.rb  module:
```rb
module Authentication
  def login_user user, password = 'login'
    user.update_attributes password: password

    page.driver.post sessions_url, {email: user.email, password: password}
    visit root_url
  end
end
```
then I included this module in my `rails_helper`
` config.include Authentication`
in my `request/session_controller.rb` file:
`let(:signed_in_user) { login_user(user) }`
I got this error:
```rb
Failure/Error: page.driver.post sessions_url, {email: user.email, pass│
word: password}
     NameError:
       undefined local variable or method `page' for #<RSpec::ExampleGroups
::ApiV1UsersSessions::DELETEApiV1UsersLogout::WhenRequestIsValid:0x0000558e
07102c60>
```
haven't figured out what was I wrong here.

**Comment by athix** [comment]
@hiendinhngoc It looks like you put your specs under `request/` which will tell RSpec that you're creating a request spec rather than a feature spec. `page` is only available when doing feature specs, as feature specs are spinning up a full application stack and testing against the user interface, while request specs are testing directly against the controller and only provide `response` (or request, I can't remember off the top of my head).

If you move your test to the `spec/features` folder it should recognize the spec correctly and work as expected.

**Comment by athix** [comment]
Closing this out, if you have any other questions feel free to ask! 😄
