### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by jcraigk** [Sorcery/sorcery#229]
As of this writing v0.13.0 is the latest version released Nov 29, 2018.  Would it be possible to cut a new release?  I am specifically interested in the Discord support added in https://github.com/Sorcery/sorcery/pull/185.

**Comment by athix** [comment]
@jcraigk the latest release is `0.14.0` released on May 22, 2019. `0.15.0` is going to be released in the near future, but there's potentially a breaking bug on master that needs to be addressed first.

In the meantime, you can use the master branch directly by updating your Gemfile to point at the master branch of this repo:

```ruby
gem 'sorcery', github: 'sorcery/sorcery', branch: 'master'
```

**Comment by jcraigk** [comment]
@athix Thanks for the fast response.

Using `branch: 'master'`, I am indeed seeing an issue where my user resource has broken associations (`ActiveRecord::InverseOfAssociationNotFoundError`), even though the `Providers::Discord` integration does work in that branch.

Using `branch: 'v0.14.0'` I am getting `uninitialized constant Sorcery::Providers::Discord` when initializing the `config.discord` parameters (I am indeed including `discord` in the `config.external_providers`) so it appears that Discord integration is broken in that branch.  This is odd because I see it included here https://github.com/Sorcery/sorcery/compare/v0.14.0...master#diff-af275996c09f414fe9c7cef361e5a00dR29

Any recommendation on a solution for one of those issues while we're waiting on v0.15.0?

**Comment by athix** [comment]
The discord PR got merged after v0.14.0 which is why it's not showing up as a part of that release.

Another option you could consider is forking and making your own branch that is in sync with the commit where discord gets merged. The primary benefit there is having a clean self-explanatory reference rather than a commit hash.

Hopefully the issue on master should be solved soon, and the discord provider can be officially released as a part of that.

**Comment by athix** [comment]
v0.15.0 has been released, and includes an important security fix as well as a fix for the loading issues.
