### ISSUE TITLE
Future of Sorcery

### ISSUE THREAD

**Issue by athix** [Sorcery/sorcery#248]
I want to open this issue to gather the opinions of the rails community, and to figure out what the future of Sorcery should look like. Currently Sorcery is intended as a lightweight alternative to Devise that lets you build out your own authentication without having to do it completely from scratch. Personally I really like this approach, but it does have some drawbacks that have shown themselves as feature creep, namely in how to handle features that are only used by a subset of developers.

Things I'd like to discuss and figure out:

* Does it still make sense to have and maintain Sorcery?
* Should Sorcery include support for OAuth and 2FA/U2F, or should that be left entirely separate and up to the developer to implement?
* If Sorcery should be kept current, what should that look like? Currently Sorcery is kept as a single library with an increasingly complex configuration file, but splititng it into multiple gems has been mentioned.

As things stand, I'm tempted to build a new authentication gem that suits my needs, and leaving Sorcery to whoever wants to take up the mantle next. That, or refactor Sorcery to be that new authentication gem (as Sorcery 1.0).

So to everyone using Sorcery, what are your thoughts?

**Comment by athix** [comment]
One thought in particular for potentially breaking down Sorcery into separate gems:

* `sorcery-core` - Session management, glues other modules together
* `sorcery-activation` - Email activation support
* `sorcery-passwords` - Username/password login, support both traditional and API-only (JWT)
* `sorcery-totp` - 2FA Authy app support
* `sorcery-webauthn` - WebAuthn support for 2FA (Dongle Auth)
* `sorcery-oauth` - OAuth login

This could be extended by the community for specific features, e.g. `sorcery-passwordless` for the magic_login submodule.

In this scenario, the existing gem (`sorcery`) would be left as-is, and would only receive security patches going forward. Then users wouldn't have to worry about their application going sideways due to a `1.0` update, and instead would have to initiate the migration process themselves. Rubygems already supports post-installation messages, so that could be used to inform users of the changes, and provide a link to a guide on how to migrate existing applications.

**Comment by jrochkind** [comment]
> As things stand, I'm tempted to build a new authentication gem that suits my needs

What might that look like? 

I don't currently use sorcery, but have in the past. Why don't I use it now? In part because of inherited projects that had already chosen devise; in part because sorcery's support/sustainability story was unclear to me. 

I think there is a place for a simple auth gem -- it doesn't make sense to be constantly reinventing the wheel in an area where mistakes have such dangerous security implications; but Devise is kind of... monstrous. There should be a very simple "just give you login" solution, which is what sorcery tried to provide.  The trick, as you say, is that it's unclear of where the boundaries of the simple auth lie, it may be that nobody needs *only* "login with a password", so the question is what else to add.  I'm not sure either; curious how starting over with a new authentication gem that suits your needs would end up different.

**Comment by athix** [comment]
@jrochkind 

>I think there is a place for a simple auth gem -- it doesn't make sense to be constantly reinventing the wheel in an area where mistakes have such dangerous security implications; but Devise is kind of... monstrous. I think many use it in a "copy paste and pray" way, because it's APIs seem so complex, which makes it hard hard to customize/integrate when you go off the beaten path.
>
>There should be a very simple "just give you login" solution, which is what sorcery tried to provide. The trick, as you say, is that it's unclear of where the boundaries of the simple auth lie, it may be that nobody needs only "login with a password", so the question is what else to add. I'm not sure either; curious how starting over with a new authentication gem that suits your needs would end up different.

I agree completely with what you've said.

> What might that look like?

My hope would be that by starting over, we could make a clean break from some of the less ideal aspects of Sorcery that have arisen due to its natural growth over time. Two big things would be enforcing good test coverage (80%+ bare minimum), and making the module system more separated to prevent becoming a smaller devise. Another key aspect would be to keep Sorcery as minimal and hackable by developers as possible; keeping the MVC separation clear, and only providing as small a set of methods as is reasonable.

> The trick, as you say, is that it's unclear of where the boundaries of the simple auth lie, it may be that nobody needs only "login with a password", so the question is what else to add.

Hopefully by breaking sorcery into multiple gems, the distinction of what people need could be created by what gems they include. Everyone has slightly different auth requirements, so by keeping the core as slim as possible you can let developers choose exactly what parts they need, without the bloat that comes with Sorcery's current module approach. This would also open the door to letting community members create their own Sorcery extensions, and having the maintenance/development burden be better spread among different people.

> As far as the current landscape of alternatives that didn't exist when sorcery started, I'm interested in rodauth, but haven't really looked it yet.

RodAuth looks very interesting, it might be worth reaching out to them and see what their stance on the ecosystem is. At a glance, I don't know if it would be a 1:1 replacement for Sorcery, but not duplicating work has strong benefits to consider. Alternatively, maybe the authors could be convinced to help build and maintain a new version of Sorcery that also satisfies their needs.

**Comment by Fustrate** [comment]
I'm probably in favor of splitting into multiple gems, from what I know of the code base. I currently use Sorcery on both of my Rails apps at work, but I don't need 80% of the different-ways-to-log-in functionality, and I'm willing to bet there are a lot of people out there in the same boat.

I think the question of creating a new gem or making changes to Sorcery depends on how big of a change you're thinking of making. If all of the database columns should be tweaked, and the auth flow logic needs some rethinking, it might just be best to start fresh and not care (so much) about a migration path for existing users. I've been meaning to get back into working on this gem, and I actually stumbled upon this issue because I'm thinking about adding `ActiveSupport::MessageEncryptor` support to this gem instead of having the `reset_password_token`/etc. fields in the database. The opportunity to make that change in a new gem instead of worrying about how existing developers would migrate that data sounds like a much cleaner path.

As for Rodauth, while it looks interesting, I'm a bit put off by how rodauth-rails seems to be "Rodauth sitting on top of Rails" instead of integrating with Rails like Sorcery does. I think Sorcery fills a spot that would otherwise be missing - fairly streamlined like Rodauth/rodauth-rails but still in line with "the Rails way" like Devise.

**Comment by athix** [comment]
@Fustrate 

> I think the question of creating a new gem or making changes to Sorcery depends on how big of a change you're thinking of making. If all of the database columns should be tweaked, and the auth flow logic needs some rethinking, it might just be best to start fresh and not care (so much) about a migration path for existing users.

I think starting fresh looks like the best route so far personally. Especially considering the massive amount of change that's been introduced to rails since Sorcery's inception.

> As for Rodauth, while it looks interesting, I'm a bit put off by how rodauth-rails seems to be "Rodauth sitting on top of Rails" instead of integrating with Rails like Sorcery does. I think Sorcery fills a spot that would otherwise be missing - fairly streamlined like Rodauth/rodauth-rails but still in line with "the Rails way" like Devise.

I agree, one of the things I love about Sorcery is that it is more or less pure ruby and plugs directly into Rails rather than any special middleware like Warden or Roda. It sounds like filling this niche would still be valuable even with the existence of RodAuth.

**Comment by ebihara99999** [comment]
@athix 
I really appreciate that you show leadership here to discussing the roadmap of Sorcery. I've been worried about less mainteners, as you mention to the maintenance/development burden.

> Does it still make sense to have and maintain Sorcery?

I think it does. Sorcery still has an advantage in providing simple APIs only needed to implement a feature.

- Comparing to devise, it is easier to cusotmize.
- Comparing to other simple authencitation gems, the advantage is: Sorcery gives simple APIs but multiple features.
I know other simpler authentication gems, which seem too simple. They are simple in both design and a feature. The design is simple and the features they offer are also simple. They just enable us to login.

> If Sorcery should be kept current, what should that look like?

I agree with the opinion to break down Sorcery into separate gems. I had the same opinion especially about the external, which would be better to be separate and have omniauth support.

#### Maintenance costs and design

It might be better the `sorcery-core` had a support for password login and password reset. But if there would exist seperate `sorcery-passwordless` gem, the traditional passowrd login would also be a separate. From the point of view of design, it's very natural.

It's the cost of maintenance that I'm worried about . Of course the maintainance cost of a gem becomes lower if the gem becomes small, but the maintainance cost is high if the number of gems increases. Though each gem has maintainers ideally in the future, the core maintainers, at the first step, manage the separate gems generated from Sorcery now. 

I don't know the good balance...

#### Features

Anyway, I would like the features as follow:

- multi scope login (as a core)
- the external module (as a different gem)
- API login with doorkeeper
- mfa support (as a different gem)
- maintenable tests ( This is not a feture, but important for mainteners )

**Comment by jrochkind** [comment]
@ebihara99999 makes a very good point -- splitting a codebase into many different gems doesn't actually decrease the total maintenance costs -- it increases it.  Keeping all those gems coordinated becomes an added challenge (for instance, wait which version of sorcery-oauth works with which version of sorcery-core? I have been in this hell with other gems)

I think the fantasy is that many gems will somehow increase the developers committed to doing maintenance too, all these new developers will show up to take ownership of different gems? Or maybe it subconsciously and "secrectly" accepts that some of these extracted gems will die on the vine; the total maintenance burden goes down, because some features in fact stop being supported at all, but you can say "well, if you want it, you are welcome to take over the gem that does that."

I think a non-backwards compat rearchitecture may be justified if you think it can result in lower maintenance burden. Whether using the sorcery name or not. I have seen that work.  But I have also seen the failure of the idea that splitting into multiple gems will somehow lower the maintenance burden. 

If you have a modular "plugin" architecture either way, what are the true motivations and pro's/con's of extracting some plugins into separate repos and gems, vs keeping them in the same repo/gem, but still need to be activated to be active? It may make sense to keep some core feature "plugins" in the core repo/gem, to actually lower the maintenance burden.

**Comment by athix** [comment]
@jrochkind 

> @ebihara99999 makes a very good point -- splitting a codebase into many different gems doesn't actually decrease the total maintenance costs -- it increases it. Keeping all those gems coordinated becomes an added challenge (for instance, wait which version of sorcery-oauth works with which version of sorcery-core? I have been in this hell with other gems)

That's a good point, and definitely a consideration. One of the major reasons behind separating things out is that it lets the dependencies be broken out so that you don't include stuff you don't need. Perhaps that could be used as the metric for what is a part of the core vs broken into its own gem. Anything that doesn't require additional dependencies could be a module directly in sorcery-core, while things that do e.g. OAuth and MFA, would be broken into add-on gems.

For the versioning, what would probably make sense is using semantic version and enforcing compatibility among the same minor/patch versions. So if you're using `sorcery-core ~> 1.0` you know that it will work with any add-on gems that are also `~> 1.0`. Whether that's practical in reality, I don't know.

For now nothing is set in stone.

**Comment by jrochkind** [comment]
> so that you don't include stuff you don't need. 

Has this actually been a real problem? Like in terms of what, code size of gem package?

**Comment by KjellMorgenstern** [comment]
I agree that splitting the code across gems would increase the maintenance, unless you plan to drop some...  but probably all submodules are used in relevant amounts.  To see which ones are used, maybe a search on github can help? A code search for `"Rails.application.config.sorcery.submodules" extension:rb path:config/initializers filename:sorcery.rb language:Ruby` looks promising, about 4500 code results. Unfortunately, the search seems not powerful enough to count the submodules used (exclude code comments), but reading through manually can give an impression.

If the test coverage can be increased, would it then be possible to 'kreep' in features like OAuth2 ?

**Comment by athix** [comment]
@jrochkind 

> Has this actually been a real problem? Like in terms of what, code size of gem package?

Yes, specifically in dependencies. If you aren't using OAuth, including sorcery for password auth should not include any OAuth dependencies. Ditto for MFA or any other submodules that are not universal. Similarly OAuth only applications should not be required to include user columns for password hash and salt. This is important at least to me personally, I don't know how others feel about dependency creep.

@KjellMorgenstern 

> I agree that splitting the code across gems would increase the maintenance, unless you plan to drop some... but probably all submodules are used in relevant amounts. To see which ones are used, maybe a search on github can help? A code search for "Rails.application.config.sorcery.submodules" extension:rb path:config/initializers filename:sorcery.rb language:Ruby looks promising, about 4500 code results. Unfortunately, the search seems not powerful enough to count the submodules used (exclude code comments), but reading through manually can give an impression.
>
> If the test coverage can be increased, would it then be possible to 'kreep' in features ?

My hope is that the increase in complexity would be offset by enforcing good test coverage from the get-go. That said, I don't have much personal experience in interlinking libraries, so I may be underestimating the work involved. Having dealt with how sub-module inclusion in Sorcery's current iteration works, I feel that it may be not as large an increase in complexity as one would assume.

If anyone has had experience in creating their own interlinked libraries please reach out to me. I would love to talk with someone that has direct experience with it. Rails itself comes to mind, with its interlinking between the different components.

**Comment by jrochkind** [comment]
> Yes, specifically in dependencies. 

Ah, I get it, absolutely I've been there, thanks. That might be a good guideline for what should be extracted into other gems, things requiring heavyweight dependencies. Other things could perhaps be left in the same gem/repo, even if using a "plugin" architecture, they could be plugins bundled with core. 

My experience with inter-linked libraries, in similar situations are... it can get very horrible, especially without sufficient developer maintenance resources.  I have been in a situation where it seemed like it would somehow be a maintenance improvement -- and it was if you only concenred yourself with maintenance of "core" -- but if you were someone who actually needed to use the extracted plugins, or felt responsibile for keeping them working, it was a nightmare. 

Note that even Rails, while being distributed as separate gems -- all the core gems are in the same repo, and they are all released simulataneously with versions in lockstep. I don't have experience doing that specifically. It avoids some of the problems -- it's developed pretty much *like* it was one gem, with CI that runs over all of it, with no need for different versions of activesupport to work with differnet versions of activerecord, the versions are just in lockstep -- but delivered as separate gems so you can avoid the dependencies you don't want. But has additional overhead in maintaining that somewhat non-standard layout and development process.  I'm not sure if I can think of any other examples that have actually done it like that.

**Comment by athix** [comment]
@jrochkind 

> Other things could perhaps be left in the same gem/repo, even if using a "plugin" architecture, they could be plugins bundled with core.

That would make sense. Develop it as a plugin system, and just let the ones with extra gem dependencies require separate gems.

>Note that even Rails, while being distributed as separate gems -- all the core gems are in the same repo, and they are all released simulataneously with versions in lockstep. I don't have experience doing that specifically. It avoids some of the problems -- it's developed pretty much like it was one gem, with CI that runs over all of it, with no need for different versions of activesupport to work with differnet versions of activerecord, the versions are just in lockstep -- but delivered as separate gems so you can avoid the dependencies you don't want. But has additional overhead in maintaining that somewhat non-standard layout and development process. I'm not sure if I can think of any other examples that have actually done it like that.

Keeping it as a lockstep setup would make sense in this scenario, imo. It would essentially be the same situation as rails, where it's all one system and the separation is primarily to manage dependencies and database requirements.

**Comment by athix** [comment]
@jrochkind the more I think about it, the more I think that making Sorcery relatively 1:1 with Rails would make sense. Its niche in the auth library world is being a rails/ruby native solution anyway, and it has very similar reasons for wanting to be multiple gems but one system.

That would also give us a solid base for how to actually implement the gem division as well, keeping the code all in the same repo and under a single CI check, but shipped as a set of gems in lockstep.

**Comment by jrochkind** [comment]
I can't think of anything else that does "related gem" releases like Rails, which makes me think it's complicated/confusing/overhead enough that it's likely to be overkill for such a simple gem as this. You need to figure out how to run CI tests accross all your gems in one repo, you need to make sure to always release all the gems together, with the same version number, and never accidentally release mismatched version numbers, and developers new to the repo are initially confused not to see the usual file layout with one-gem-per-repo and a gempsec at the top level. 

But it's your call! You can certainly try to work it out!

**Comment by athix** [comment]
@jrochkind do you know of any simpler release systems that would support not having unnecessary dependencies? I would like to avoid extra overhead if possible.

Looking at how rails implements the lockstep functionality, at least that part would be pretty straight forward. Your point on repo structure is very valid though, so looking into alternatives makes sense.

**Comment by jrochkind** [comment]
Not really. The only other option we haven't yet talked about is not formally declaring the dependency, having it be sort of a "soft optional" dependency. 

This definitely has a lot of downsides, but is sometimes done anyway as the least-bad option.  For instance, rails doesn't formally declare a dependency on postgres or mysql or any other db. If you try to use a database adapter without having the gem in your own gemfile, it will complain. It even knows what versions of the pg or mysql gem it wants, and if you try to use a different _version_ than it wants, it will complain -- but all done on it's own without actually declaring the dependency officially. 

This definitely has it's own problems and downsides. I wrote some things about it some time ago here: https://bibwild.wordpress.com/2015/09/09/optional-gem-dependencies/

Definitely your choice of least bad options here. 

I think if I were you, I probably would go ahead and remove certain especially heavy-weight things to separate gems, just in the normal way, with separate repos. But I'd do this with as few things as possible, only if they actually HAVE been causing pain by having very heavy-weight or often-conflicting dependencies. I'd try to leave as much as possible in the main gem/repo.  (There are also examples of this; the shrine gem for file handling has many many plugins in the same gem/repo, but certain ones in separate gems and repos). But that's just my own personal call on the least bad option.

**Comment by Fustrate** [comment]
I think the most reasonable path forward is to load most of the internal submodules as internal plugins - don't remove them from the gem, but load them in the same manner as you would an external gem. The furthest you should need to go is to make 3 gems: `sorcery`, `sorcery-external`, and `sorcery-mfa`. The other features of Sorcery are all too closely related to make sense extracting.

On a related "future of Sorcery" note, I think the current initializer could be cleaned up quite a bit, both to make loading any external plugins/providers easier, and to remove redundant information. To that end, I created a quick example showing how I think internal and external plugins and providers could be loaded and configured.

https://gist.github.com/Fustrate/6280bbf3f22290bb22c03146af6999ac

I'm not in love with the mega-hash, so I think I prefer calling `add_provider` multiple times, once for each enabled provider, and possibly doing the same thing for the plugins/submodules if the user config merges upwards. It would also make the documentation of each thing a bit more clear, instead of needing to comment/uncomment in the middle of a hash.

**Comment by athix** [comment]
This has been incredibly helpful, thank you @jrochkind, @Fustrate, @ebihara99999, and @KjellMorgenstern!

I think this has given me some good ideas on how to approach revitalizing Sorcery, although I still welcome anyone using Sorcery to chime in with any thoughts or suggestions. I'll be working on reworking the module system to be a flexible plugin system, and only extract the biggest non-core items into separate plugins (currently `mfa` and `oauth`). Improving the API support of Sorcery will also be a major focus, as that is an area that I intend to be using it for personally.

As for long term support and sustainability, I will be stepping up my personal time commitment towards Sorcery going forward. While I can't give a firm timeline on Sorcery v1, I'll be spending a minimum of 10-20 hours a week working on it for the foreseeable future.

**Comment by crimson-knight** [comment]
I was away on vacation for the 4th when this conversation started--but here's my late $0.02!

I think we can radically simplify most of what sorcery does now, but without splitting it up into too many gems. Maintaining multiple gems in lockstep is a real pain, I've been doing it for a large internal tool we have for one project and I've seriously hated myself for going that route when we didn't have to. Honestly, most gems aren't very big and have overlapping dependencies that are already installed on the system, so it's rarely adding much. Adding a major library as a dependency for a single feature though--that's almost always a reason to write your own version of the task. Adding many features/methods/functionality that another library already does is reason enough to include it and use it.

I agree most of the current submodules should be considered the "core" with Omniauth (`oauth`) and 2FA (`mfa`) being extracted out as separate gems. Both of those add complexity that should, and needs to, be configured separately from Sorcery's core functionality.

I would really like to contribute something that allows for teams/permissions based on a user role and/or inherited user Model of some kind. I noted this on a PR but I'm throwing it in here as well. It's a major pain point for me, and I'm certain I'm not the only one who's been cobbling together lack-luster permissions systems for their projects. They work (of course), but chances are they are cumbersome, repetitive and probably have holes in them we don't realize (and hopefully never discover the wrong way!)

**Comment by crimson-knight** [comment]
PS: I highly prefer Sorcery over Devise. I think we can get a larger user base if we clean up the docs. That would be best done as the upgrades/refactoring happen.

In the meantime, I think I'll write some templates for www.railsbytes.com and see if I can get some tutorials written using Sorcery and see if we can get some more traction with users this way. The more people using the gem, the more of a reason to maintain it, right? 😁

**Comment by athix** [comment]
@crimson-knight The documentation has been struggling heavily so any help getting that modernized would be greatly appreciated! A lot of it was written for Rails 3/4, so quite a bit has changed since then.

**Comment by pama** [comment]
I think it makes sense to have and maintain Sorcery.

I agree that both OAuth and 2FA/U2F don't belong to the core, but I don't see the advantage of splitting the source code in tiny gems.

By Sorcery Philosophy less is more and we should keep that in mind. I think we are all here because of that. A tiny API, with what is necessary to bootstrap authentication, with our own workflow.

**Comment by athix** [comment]
I think a solid plan is in place, so I'm going to close this out with a TL;DR for people reading this issue in the future:

* Sorcery does still make sense within the Rails ecosystem.
* I'll be commiting at least 10-20 hours a week to working on Sorcery for the foreseeable future.
* Sorcery's submodule system will be reworked into a plugin system.
  * The 'External' submodule for OAuth will be migrated into a plugin kept in `sorcery-oauth`.
  * All other existing Sorcery functionality will be kept as plugins in `sorcery-core`.
  * A new plugin will be created for 2FA/MFA support as a part of `sorcery-mfa`.
* Sorcery::Config will be simplified to reduce complexity without affecting functionality. @fustrate's [gist](https://gist.github.com/Fustrate/6280bbf3f22290bb22c03146af6999ac) will likely be used as a base for this.
* Any new functionality will be included in `sorcery-core` if there are no gem dependencies needed for it. (No need to create a ton of tiny gems)
* The core principal of "Less is more" will be kept going forward. Any additions and changes will be kept as small as possible to support usage in existing MVC structures.

**Comment by janko** [comment]
I just wanted to comment on the Rodauth evaluation, as I felt it has been fairly brief. I'm the author of rodauth-rails, and am interested in understanding the Ruby/Rails community's preferences for authentication. The reason I'm trying to promote Rodauth is because it's the first full-featured solution that works with *any* Ruby web framework (not just Rails), and it's *really* good. I would personally like to see the Ruby ecosystem in general to be moving in that direction – towards good libraries that are accessible to everyone.

> As for Rodauth, while it looks interesting, I'm a bit put off by how rodauth-rails seems to be "Rodauth sitting on top of Rails" instead of integrating with Rails like Sorcery does. I think Sorcery fills a spot that would otherwise be missing - fairly streamlined like Rodauth/rodauth-rails but still in line with "the Rails way" like Devise.

Yeah, that approach is definitely different than most other Rails-based authentication frameworks (though it's similar to how Warden works). However, I'd argue that this is an advantage rather than a limitation. This way your authentication logic is decoupled from your Rails app and is all defined in one place, and can even be applied for mounted Rack apps (e.g. for authenticating access to Sidekiq's web UI). I don't see any concrete downsides of this approach.

I actually think that extending Rails components (models, controllers) is not ideal from the design perspective, because it's violating the Single Responsibility Principle – your AR models now also deal with authentication and sending emails. Note that I'm not trying to criticize Sorcery's design; I think the Rails Way in general encourages putting logic into AR models that doesn't really belong there. Yes, much of Sorcery's model logic *is* database-related, but it can still be performed outside of the model.

The approach that Rodauth took with decoupling from Rails brought in many advantages, such as consistent before/after hooks for every action, unified configuration API that allows overriding virtually any behaviour, and authentication features that are decoupled from each other and contained in a single place (only one file per feature). Many features that are on Sorcery's roadmap or which someone PR'd are already implemented in Rodauth:

* MFA (TOTP, SMS codes, recovery codes, WebAuthn)
* JWT support
* single session

In addition to this, most open issues and pull requests here are already solved in Rodauth too. The only feature I've seen that Rodauth is currently missing is OmniAuth integration, but people can use OmniAuth directly for the time being.

**Comment by athix** [comment]
> I'm the author of rodauth-rails, and am interested in understanding the Ruby/Rails community's preferences for authentication.

Hi @janko! I can't speak for the rest of the Ruby on Rails community, but I can share some of my thoughts on this.

> I just wanted to comment on the Rodauth evaluation, as I felt it has been fairly brief.

I want to clarify a little on why my Rodauth evaluation was so brief, as I sense there may be some frustration that it wasn't given a longer look:

My reason for not spending too much time evaluating RodAuth isn't because it looked bad or insufficient at all. It's more that there is a difference in design goals that are mutually exclusive, and Sorcery / RodAuth fill different niches in the Ruby ecosystem. Some of the points you bring up are actually because of those design goal differences, so I'll comment further on those specific parts.

> The reason I'm trying to promote Rodauth is because it's the first full-featured solution that works with any Ruby web framework (not just Rails), and it's really good. I would personally like to see the Ruby ecosystem in general to be moving in that direction – towards good libraries that are accessible to everyone.

Making a framework agnostic library is a great idea, and I'm glad that you're helping those not using Rails by creating something that works with those other frameworks as well as Rails. There is however a significant cost that comes with this approach though, which is additional code complexity.

Part of the appeal behind Sorcery, and the reason I've decided to continue work on it, is because there aren't any other libraries that are intentionally very simple to grok, and don't get in your way. Sorcery is essentially as close to writing the auth yourself in the first place as you can get, and I think that's why many developers are drawn to it.

> Yeah, that approach is definitely different than most other Rails-based authentication frameworks (though it's similar to how Warden works). However, I'd argue that this is an advantage rather than a limitation. This way your authentication logic is decoupled from your Rails app and is all defined in one place, and can even be applied for mounted Rack apps (e.g. for authenticating access to Sidekiq's web UI). I'm curious if you see any specific downsides to this approach.

I think the limitation is that the authentication logic _is_ decoupled from the Rails app. If all you're trying to do is add a simple login flow to a Rails App, having an entirely different subsystem is a lot of code to have to grok and potentially overkill.

> I actually think that extending Rails components (models, controllers) is not ideal from the design perspective, because it's violating the Single Responsibility Principle – your AR models now also deal with authentication and sending emails. Note that I'm not trying to criticize Sorcery's design; I think the Rails Way in general encourages putting logic into AR models that doesn't really belong there. Yes, much of Sorcery's model logic is database-related, but it can still be performed outside of the model.

Sorcery also makes a point of keeping responsibilities contained, but the division is more in-line with what Rails does than a true Single Responsibility Principle approach. Sorcery is coupled very tightly with how Rails implements MVC, keeping the Models (database) and Controllers (session) separate. With Sorcery, doing things the Rails way is very much intentional.

A core ideal of Sorcery is that if you want to do things differently, you shouldn't have to fight the library to do it. I feel that creating a custom authentication layer would go counter to that ideal, but if there are ideas on how to implement it I would be interested to know more.

>The approach that Rodauth took with decoupling from Rails brought in many advantages, such as consistent before/after hooks for every action, unified configuration API that allows overriding virtually any behaviour, and authentication features that are decoupled from each other and contained in a single place (only one file per feature).

All three of these are great ideas! The code separation is actually already a major part of the Sorcery v1 rework, but both the action hooks and unified config API are interesting ideas that I'll look into for v1. Thank you! :smile: 

> Many features that are on Sorcery's roadmap or which someone PR'd are already implemented in Rodauth:
>
> * MFA (TOTP, SMS codes, recovery codes, WebAuthn)
> * JWT support
> * single session
>
> In addition to this, most open issues and pull requests here are already solved in Rodauth too. The only feature I've seen that Rodauth is currently missing is OmniAuth integration, but people can use OmniAuth directly for the time being.

Again, the hesitation with Rodauth isn't a lack of functionality, but a difference in design goals. It looks like a very well done library, and I feel that both Sorcery and Rodauth can coexist in the Ruby ecosystem by filling different niches. I hope you agree as well.

**Comment by janko** [comment]
I appreciate your reply @athix 👍 

> [...] There is however a significant cost that comes with this approach though, which is additional code complexity.
> 
> Part of the appeal behind Sorcery, and the reason I've decided to continue work on it, is because there aren't any other libraries that are intentionally very simple to grok, and don't get in your way. Sorcery is essentially as close to writing the auth yourself in the first place as you can get, and I think that's why many developers are drawn to it.

I see, that makes sense. Yeah, Sorcery is indeed very simple to grok, and that definitely reduces the learning curve, compared to something like Rodauth.

Rodauth's goal is definitely different from that perspective, in it that it provides complete implementation of routes for each action (login, create account, verify account, reset password etc). You do have the tools to customize that flow, but you first have to learn Rodauth's implementation. And with Sorcery you're in charge from the start.

> I think the limitation is that the authentication logic is decoupled from the Rails app. If all you're trying to do is add a simple login flow to a Rails App, having an entirely different subsystem is a lot of code to have to grok and potentially overkill.

Yeah, that makes sense. In my case I know it will never be just a simple login flow, that I'll always end up needing much more authentication features, so I want to already start with something that I can build upon in the future. But in simpler scenarios choosing something lighter makes sense.

> Sorcery also makes a point of keeping responsibilities contained, but the division is more in-line with what Rails does than a true Single Responsibility Principle approach. Sorcery is coupled very tightly with how Rails implements MVC, keeping the Models (database) and Controllers (session) separate. With Sorcery, doing things the Rails way is very much intentional.

Yeah, I suppose that's a fundamental difference in my approach, which is that most of the business logic should live outside of the Rails layer. In Rodauth's case, it defines all its behaviour in a dedicated `Rodauth::Auth` class, which has access to Rack's request context and the database. That means you still have access to things like sessions, flash messages, routing, view rendering, retrieved database records etc, but you're just not inside of a controller or a model.

> Again, the hesitation with Rodauth isn't a lack of functionality, but a difference in design goals. It looks like a very well done library, and I feel that both Sorcery and Rodauth can coexist in the Ruby ecosystem by filling different niches. I hope you agree as well.

Yeah, this makes more sense to me after this discussion. I personally have this quest to avoid fragmentation in the Ruby community, but there are no silver bullets of course. And in this case I'm also biased towards Rodauth's approach, because I'm already a huge fan of other Jeremy Evans' libraries, and I had decent experience using other Ruby web frameworks, so I want to invest in libraries I can use with both Rails and other frameworks. But Sorcery's design is definitely suitable for those who prefer to stay close to Rails 👍

**Comment by inopinatus** [comment]
I'm a small voice and late to the party, but I wanted to say a) thanks for all the work that's been put into Sorcery, from a appreciative user, and that b) one of my reasons for preferring Sorcery is that it _doesn't_ depend on Omniauth and supplies an alternative instead. Make of that what you will.

**Comment by cpanderson** [comment]
Also late to the party and want to say thank you for this great gem. I found Devise too unwieldy and use Sorcery exclusively now. Maybe it's mentioned above but would it be helpful to be on Github Sponsers? I would contribute to help with the effort as I'm sure others would as well.

**Comment by joshbuker** [comment]
GitHub sponsors does serve as signal for me to provide more time to maintaining Sorcery and developing v1. That said, there already have been enough folks kind enough to donate to justify me doing so, and I am committed to releasing v1 no matter what at this point.

What would help things move forward the quickest is additional folks willing to help maintain the code and work on v1. That said, sponsorship does help light more a fire under my butt. :stuck_out_tongue_winking_eye: 

Glad to hear folks are still getting use out of the Sorcery, and I'm excited to give it some fresh life by adding support for things like FIDO2 and updating the SSO to use Omniauth!

**Comment by imageaid** [comment]
Also late to the game but wanted to let you know that we're switching our monolith to Sorcery from Clearance. We just found Sorcery's API and straight-forward approach to authentication a huge help for our app, which has very basic, simple authentication needs compared to many apps. 

Thanks, very much, for all the work on Sorcery and for staying with it. My fellow developer and I will try and further chip in to help with the library in the coming months as we delve further into using Sorcery, etc.!
