### ISSUE TITLE
InstanceMethods of remember_me for Model aren't included

### ISSUE THREAD

**Issue by gallifreyfalls** [Sorcery/sorcery#71]
Why can't I use methods forget_me! and remember_me! as they're missing for the User class?
Submodule is enabled and everything works fine, e.g. login when remember is false
```ruby
Rails.application.config.sorcery.submodules = [:remember_me]
```
```ruby
if @user = login(email, params[:password], params[:remember])
    render json: {'login' => 'successful'}.to_json
else
    render json: {'login' => 'failed'}.to_json
end
```
```ruby
class User < ApplicationRecord
  authenticates_with_sorcery!
...
end
```
Necessary fields are also created in the database

**Comment by athix** [comment]
I just tried this on my personal website using Sorcery 0.11.0 and Rails 5, and can't seem to replicate any issues calling either method. Would you mind posting the stack trace so I can track down the issue?

Based on [this comment](https://github.com/Sorcery/sorcery/blob/master/lib/sorcery/model/submodules/remember_me.rb#L41), you might have issues if you're trying to call the method directly on the user instead of letting the controller method do it.
