### ISSUE TITLE
Is there a way to integrate 2FA with Sorcery?

### ISSUE THREAD

**Issue by shuke0327** [Sorcery/sorcery#72]
integrate 2fa(2 factor authentication) with sorcery, is there a way?

**Comment by athix** [comment]
That's a great question, I haven't tried yet honestly. Assuming there's a library, you could modify your login method to include 2fa but I don't think there's any explicit support built-in. I could help more if you tell me what version of 2fa you're using and how you want the login flow to work.

**Comment by shuke0327** [comment]
＠athix thanks for your reply. In my project, I use twilio to send out sms with verification code for 2fa, and record the temp verification code as well as the user id in memcached.And, for the login and logout, I overwrite the methods provided in sorcery, namely:

since require_login used the logged_in? method, so I use alias method in Rails, the fake code like this:

alias_method :old_logged_in?, :logged_In?

def logged_in_with_2fa?
 logged_in? && !require_2fa_verification?
end

alias_method :logged_In?, :logged_in_with_2fa?

the require_2fa_verification? listed above is used to judge for if the current user need to perform a 2fa process.

and for logout, since the method provided by sourcery used:


def logout
   if logged_in?
　xxxx
end

so, I have to rewrite it as follows:

def logout
  if !!current_user?
  xxx
end

since the logged_In? method has been over write with require_2fa_verification? 

wish I have make it clear to state my process.

Actually, I think there should be a much easier and more elegent way to integrate 2fa into sourcery.
 hope the stuffs above could invoke some thinking.

thanks for your time, @athix, and thanks for your bringing in such a great project as Sorcery.

**Comment by athix** [comment]
Hey @shuke0327, sorry for the late response!

I would recommend not overwriting the Sorcery methods, as you found out it can cause a whole slew of unintended side-effects. Instead, what I would recommend is changing your OAuth / Session controllers so that they include the `require_2fa_verification?` as a part of their flow.

I believe there's currently no way to check if a password is correct without logging in and logging out immediately, but I require something similar for something else I'm doing, so we could actually kill two birds with one stone there.

How I would recommend approaching it:

1. User attempts to login with either oauth or username/password combo.
2. Controller verifies that user is valid, and auth would be successful (new method)
3. `require_2fa_verification?` is checked, and the user is either immediately logged in, or directed to the 2fa form.
4. If the latter, hold reference of the user and auto-login if 2fa is successful.

If this sounds like it would work for you, I'll create a pull request with the new method both of us need and include it in the next Sorcery release.

**Comment by athix** [comment]
Closing, please reopen this issue if you still need help!
