### ISSUE TITLE
Server side session termination

### ISSUE THREAD

**Issue by Sanjay-Chaudhary** [Sorcery/sorcery#91]
How do i do this: I want to do **server side session termination** - hacker can still login into the system using cookie even after the user has loges out ....

**Comment by Ch4s3** [comment]
does `force_forget_me!` serve your needs?

**Comment by Sanjay-Chaudhary** [comment]
Do i need to call force_forget_me! in application controller?
Can u please give bit more info where n how to implement this?

**Comment by Ch4s3** [comment]
It should be called on logout by this line if you're using remember_me. https://github.com/Sorcery/sorcery/blob/4e3fcdb8df16912424281322ce9f2862937846fc/lib/sorcery/controller/submodules/remember_me.rb#L22

Can you provide a concrete case where tokens can be used after logout?

**Comment by Sanjay-Chaudhary** [comment]
Thanks for the quick response....
But i am not using remember_me...
So now how can i terminate server side session.
Secondly does sorcery takes care of this scenario... I login into the site. go into some page. copy the URL and close the browser... i am not logging out from website here. Now i open a new browser and past the same URL and that pages open in the new browser. Which should not happen. That means the session is still active. It should force the user to login again. But this is not happening. This can be a security issue. So can you please help me telling if this is possible using sorcery. If yes then can you please give me some details. Thanks

**Comment by Ch4s3** [comment]
You would need to know when a user navigates away from a page to do that, but I'm not sure what the issue is here. If a user closes the page and without logging out and then in the same browser visits the page again, their cookie is still valid. This is expected and normal behavior. The cookie only exists in that browser and that machine, so it shouldn't be a problem.

What attack scenario are you imagining? Are you trying to prevent a second person on the same machine accessing the page? If so, use session timeouts and set a low number of minutes.

**Comment by athix** [comment]
No movement for two years, closing...
